### ISSUE TITLE
.NETをインストールしないといけない

### ISSUE THREAD

**Issue by hohjukgi** [RFTtama/Moni#33]
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=6.0.21

**Comment by hohjukgi** [comment]
https://dotnet.microsoft.com/ja-jp/download/dotnet/6.0/runtime?cid=getdotnetcore&os=windows&arch=x64

**Comment by RFTtama** [comment]
説明に追記すること
